### ISSUE TITLE
options hash provided to subcommands is not intuitive

### ISSUE THREAD

**Issue by leemhenson** [davetron5000/gli#216]
Hi

If I define a command structure:

```ruby
command :outer do |outer|
  outer.flag 'outer-flag'
  command :inner do |inner|
    inner.flag 'inner-flag'
    inner.action do |global_options, local_options, args|
      # ...
    end
  end
end
```

... and then I invoke it like this:

```
gli --outer-flag='abc' outer --inner-flag='xyz' inner
```

... the ```local_options``` argument in the action block contains a weird looking hash (symbol args not shown here for brevity):

```ruby
{
  "inner-flag" => "xyz",
  #<Object:0x007fdaf4312500> => {
    #<Object:0x007fdaf4312500> => {
      "outer-flag" => "abc"
    }
  }
}
```

What's the thinking here? It looks like ```#<Object:0x007fdaf4312500> == GLI::Command::PARENT``` if that's any help. I would have thought something like this would make more sense:

```ruby
{
  "outer" => {
    "outer-flag" => "abc"
  },
  "inner" => {
    "inner-flag" => "xyz"
  }
}
```

**Comment by davetron5000** [comment]
I used an object instead of a string so you could unambiguously determine that it was referencing the parent command's options.

The idea would be that you can always access your options via `options[:flag]`, i.e. without having to know which command you are.  And if you want the options passed to your parent, you can do `options[GLI::Command::PARENT][:flag]` and not have to know the name of your parent.

I will admit that the subcommand option handling was incredibly tricky and went through a few iterations.  This seemed to be a design that would not break backwards compatibility.  I haven't had need to create complex CLI apps with deeply-nested subcommand hierarchies, so I was mostly focused on not having to do a major version bump.

**Comment by leemhenson** [comment]
Yeah I get it. Personally speaking, it makes a bit more sense that you would attempt to grab an option value via it's owning command name, rather than thinking in terms of "how many nodes are there between the current command and the command that owns the option I want". No biggy though, I don't have duplicate option names across my commands so I've written a class that will recursively search 'up the tree' to find the option name I'm interested in.

**Comment by davetron5000** [comment]
Yeah, the original design of subcommands requires that all options be unique across all commands, but that ended up being overly constraining and confusing to some users.
