### ISSUE TITLE
Flag's required is not enforced on CLI

### ISSUE THREAD

**Issue by itsSaad** [davetron5000/gli#251]
im using it as:
````
  c.flag [:e, :environment], arg_name: 'environment_name', desc: "Environment to provision", type: "String", required: true
````
`requried: true` is there. but when i use it as `bundle exec bin/face provision` on command line. One expects to see an error mentioning you missed a required flag.But it goes through without.

**Comment by davetron5000** [comment]
This isn't broken for me—can you post your repo or a minimal repo that reproduces this?

**Comment by itsSaad** [comment]
Sorry for trouble. Actually it works. mine wasnt because mine was raising a `#<LocalJumpError: unexpected return>` when i used `return true` in the pre block instead of `true`.
Do you know what that is about?

**Comment by davetron5000** [comment]
Yeah, `return` in Ruby is only really intended to be used inside a method definition.  If you use it inside a block (which is what `pre` is taking), Ruby tries to return from whatever method that block is.  My guess is that it's confused because in your GLI app, you aren't inside a method, but in the special `main` object.    [This stackoverflow](http://stackoverflow.com/questions/2325471/using-return-in-a-ruby-block) question has a bit more detail.

**Comment by itsSaad** [comment]
oh. thanks a lot for clearing that up. never thought of it for the last 4 years.
